### ISSUE TITLE
Unknown filter plugin 'fields_parser'

### ISSUE THREAD

**Issue by rossKayHe** [fluent-plugins-nursery/fluent-plugin-kv-parser#8]
Is this repo out of date?  I'm looking for something that will parse a field from a log as kv pairs.
The log is tab delimited up to a point using a data dictionary, then kv pairs on the end of the line.
field:value,field2:value2 with space,field3:value3

**Comment by kenhys** [comment]
* If you use Fluentd v.1.1.0 or later, it is better to use https://docs.fluentd.org/parser/ltsv.

* `Unknown filter plugin 'fields_parser' ` means that you need to install `gem install fluent-plugin-fields-parser`.

* I'm not sure, but it may work:

```
<source>
  @type tail
  path sample.log
  read_from_head true
  tag test
  <parse>
    @type kv
    kv_delimiter ,
    kv_char :
  </parse>
</source>

<match **>
  @type stdout
</match>
```

**Comment by kenhys** [comment]
I'll close this issue because the report is stale for a long time and no sample fluent.conf from the submitter, so it is hard to guess to support to some extent.
